### GET: All Books
GET http://localhost:8080/api/v1/books/
Accept: application/json
###


### GET: Get Book
GET http://localhost:8080/api/v1/books/find/45
Accept: application/json
###


### POST: Add Book
POST http://localhost:8080/api/v1/books/add
Content-Type: application/json
Accept: application/json

{
  "isbn": "111-236-857",
  "accessionNumber": "221254",
  "title": "Today is Good!",
  "author": "John Tom",
  "status": "Available"
}
###


### DELETE: Delete Book
DELETE http://localhost:8080/api/v1/books/delete/1
Accept: application/json
###


### DELETE: Delete All Books
DELETE http://localhost:8080/api/v1/books/delete-all
Accept: application/json
###


### PUT: Update Book
PUT http://localhost:8080/api/v1/books/update/9791964934357
Content-Type: application/json
Accept: application/json

{
  "isbn": "9791964934357",
  "title": "Edna O'Brien",
  "author": "Thaddeus Moen",
  "status": "Available",
  "accessionNumber": "ACC-0003-O1276",
  "loan": {
    "id": 1,
    "borrowDate": "2000-05-10T00:00:00",
    "returnDate": "2000-05-10T00:00:00",
    "member": null,
    "book": null
  },
  "lateFee": null
}
###


### GET: Async Task
GET http://localhost:8080/api/v1/faker/generate-books/20
Accept: application/json

